global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "postgres"
    static_configs:
      - targets: ["pg-exporter:9187"]

  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:9464"]
